export const vehiclesData = [
  {
    name: "H6 Supreme",
    model: "SUV Híbrido Premium",
    slug: "h6-supreme",
    image: "/h6-hev-celeste.jpg",
    price: "Consultar",
    features: {
      engine: "1.5T + Motor Eléctrico",
      transmission: "DHT Automática",
      seats: "5 Pasajeros",
    },
    badge: "Híbrido",
    description:
      "El Haval H6 HEV Supreme combina la eficiencia de un motor híbrido con el lujo y la tecnología más avanzada. Con una potencia combinada de 243 HP y un consumo excepcional, es la opción perfecta para quienes buscan rendimiento y economía.",
    specs: {
      motor: "1.5T + motor eléctrico",
      potencia: "243 HP",
      torque: "530 Nm",
      transmision: "Caja automática DHT",
      traccion: "2WD",
      bateria: "1.76 kWh",
      consumo: {
        ciudad: "4.3 L/100 km",
        ruta: "5.8 L/100 km",
        mixto: "5.6 L/100 km",
      },
      dimensiones: "4.683 x 1.886 x 1.730 mm",
      entreEjes: "2.738 mm",
      pesoBruto: "2.140 kg",
    },
    equipamiento: [
      "Techo panorámico",
      "Portón eléctrico",
      "Tapizado en cuero",
      "Climatizador bizona",
      "Purificador de aire",
      'Pantalla 12.3"',
      "Android Auto + Apple CarPlay",
      "Cargador inalámbrico",
    ],
    seguridad: [
      "6 airbags",
      "AEB (Frenado Autónomo de Emergencia)",
      "ACC (Control de Crucero Adaptativo)",
      "LKA (Asistente de Mantenimiento de Carril)",
      "BSD (Detección de Punto Ciego)",
      "Cámara 360°",
      "W-HUD (Head-Up Display)",
      "TPMS (Monitor de Presión de Neumáticos)",
    ],
    garantia: "3 años o 100.000 km",
  },
  {
    name: "H6 Deluxe",
    model: "SUV Mediano",
    slug: "h6-deluxe",
    image: "/h6-hev-celeste-deluxe.jpg",
    price: "Consultar",
    features: {
      engine: "2.0L Turbo",
      transmission: "Automática",
      seats: "5 Pasajeros",
    },
    description:
      "El Haval H6 Deluxe ofrece un equilibrio perfecto entre confort, tecnología y rendimiento. Con un diseño elegante y equipamiento completo, es ideal para la familia moderna.",
    specs: {
      motor: "2.0L Turbo 4 cilindros",
      potencia: "201 HP",
      torque: "320 Nm",
      transmision: "Automática",
      traccion: "2WD",
      dimensiones: "4.653 x 1.886 x 1.730 mm",
      entreEjes: "2.738 mm",
      pesoBruto: "2.075 kg",
    },
    equipamiento: [
      "Techo panorámico",
      "Tapizado en cuero",
      "Climatizador bizona",
      'Pantalla multimedia 10.3"',
      "Android Auto + Apple CarPlay",
      "Cargador inalámbrico",
      "Apertura eléctrica de baúl",
    ],
    seguridad: [
      "6 airbags",
      "AEB (Frenado Autónomo)",
      "ACC (Control de Crucero Adaptativo)",
      "LKA (Asistente de Carril)",
      "BSD (Punto Ciego)",
      "Cámara 360°",
      "TPMS",
    ],
    garantia: "3 años o 100.000 km",
  },
  {
    name: "Tank 300",
    model: "SUV Off-Road 4x4",
    slug: "tank-300",
    image: "/tank-300-naranja.jpg",
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_5-tyOmFDF5nY9Xcmg0JA7ZkIze6WCrt7.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_6-VrMPqFTdT5FJ2thXzjUk2CCK3kqfng.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_4-73Q4vha0exuOcJ3LT297libT1s7rxc.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_2-7taquY6jrAq6TcclyHEdVbJF3jd09n.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_1-VxZJf6YfJABUIKRWq4S0RQ6HVAHnRt.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tank-V2_galeria_3-AD75YJPPRMXIJJ3diThpR6iIDmdLnt.webp",
    ],
    price: "Consultar",
    features: {
      engine: "2.0L Turbo",
      transmission: "Automática 8 vel.",
      seats: "5 Pasajeros",
    },
    badge: "Off-Road",
    description:
      "El GWM Tank 300 es el 4x4 definitivo que combina fuerza bruta con tecnología de punta. Con tracción 4x4, reductora y múltiples modos de conducción, está listo para cualquier aventura.",
    specs: {
      motor: "2.0L Turbo",
      potencia: "217 HP",
      torque: "380 Nm",
      transmision: "Automática 8 velocidades",
      traccion: "4x4 automática Torque on Demand (TOD)",
      diferenciales: "Delantero, trasero y central con bloqueo eléctrico",
      modosConducta: ["Estándar", "Nieve", "Bache", "Roca", "Montaña", "Barro"],
      dimensiones: "4.760 x 1.930 x 1.900 mm",
      capacidadBaul: "Hasta 1.635 L",
      tanque: "70 L",
    },
    equipamiento: [
      "Asientos en cuero napa eléctricos",
      "Asientos calefaccionados y ventilados",
      "Climatizador bizona",
      "Techo solar",
      'Pantalla táctil 12.3"',
      "Audio Infinity con subwoofer",
      "Cargador inalámbrico",
      "Cargadores USB delanteros y traseros",
      "Toma 220V en baúl",
      "Mesa de picnic integrada",
      "Faros full LED",
      "Barras de techo",
      "Pack estético off-road",
      "Ganchos de remolque",
      "Estribos fijos",
    ],
    seguridad: [
      "6 airbags",
      "ESP, TCS, RMI",
      "HHC/HDC (Asistente de arranque y descenso)",
      "ACC (Control de Crucero Adaptativo)",
      "AEB (Frenado Autónomo)",
      "Detector de punto ciego",
      "Alerta de colisión delantera y trasera",
      "Mantenimiento de carril",
      "Cámaras 360°",
      "8 sensores de estacionamiento",
    ],
    garantia: "Motor y transmisión: 10 años o 1.000.000 km (primer dueño) | Vehículo completo: 6 años o 200.000 km",
  },
  {
    name: "Jolion Supreme",
    model: "SUV Compacto Premium",
    slug: "jolion-supreme",
    image: "/jolion-azul.jpg",
    price: "Consultar",
    features: {
      engine: "1.5L Turbo",
      transmission: "DCT 7 velocidades",
      seats: "5 Pasajeros",
    },
    description:
      "El Haval Jolion Supreme es el SUV compacto perfecto para la ciudad. Con tecnología avanzada, diseño moderno y excelente eficiencia, ofrece todo lo que necesitas en un paquete compacto.",
    specs: {
      motor: "1.5L Turbo 4 cilindros",
      potencia: "141 HP (5.600-6.000 rpm)",
      torque: "210 Nm (2.000-4.400 rpm)",
      transmision: "DCT 7 velocidades",
      traccion: "2WD",
      dimensiones: "4.472 x 1.841 x 1.619 mm",
      entreEjes: "2.738 mm",
      pesoBruto: "1.740 kg",
    },
    equipamiento: [
      "Tapizado cuero ecológico",
      "Techo panorámico",
      "Climatizador bizona",
      'Pantalla multimedia 12.3"',
      "Apple CarPlay / Android Auto",
      "Carga inalámbrica",
      "Sensores y cámara 360°",
    ],
    seguridad: [
      "6 airbags",
      "ESP, TCS",
      "AEB (Frenado Autónomo)",
      "LDW (Alerta de Cambio de Carril)",
      "ACC (Control de Crucero Adaptativo)",
      "BSD (Detección de Punto Ciego)",
      "TPMS",
      "DFMS (Sistema de Monitoreo de Fatiga)",
    ],
    garantia: "3 años o 100.000 km",
  },
  {
    name: "Jolion Deluxe",
    model: "SUV Compacto",
    slug: "jolion-deluxe",
    image: "/jolion-azul-deluxe.jpg",
    price: "Consultar",
    features: {
      engine: "1.5L Turbo",
      transmission: "DCT 7 velocidades",
      seats: "5 Pasajeros",
    },
    description:
      "El Haval Jolion Deluxe combina estilo, tecnología y eficiencia en un SUV compacto ideal para el uso diario. Perfecto para quienes buscan calidad y equipamiento a un precio accesible.",
    specs: {
      motor: "1.5L Turbo 4 cilindros",
      potencia: "141 HP (5.600-6.000 rpm)",
      torque: "210 Nm (2.000-4.400 rpm)",
      transmision: "DCT 7 velocidades",
      traccion: "2WD",
      dimensiones: "4.472 x 1.841 x 1.619 mm",
      entreEjes: "2.738 mm",
      pesoBruto: "1.740 kg",
    },
    equipamiento: [
      "Tapizado cuero ecológico",
      "Techo panorámico",
      "Climatizador bizona",
      'Pantalla multimedia 12.3"',
      "Apple CarPlay / Android Auto",
      "Carga inalámbrica",
      "Sensores y cámara 360°",
    ],
    seguridad: [
      "6 airbags",
      "ESP, TCS",
      "AEB (Frenado Autónomo)",
      "LDW (Alerta de Cambio de Carril)",
      "ACC (Control de Crucero Adaptativo)",
      "BSD (Detección de Punto Ciego)",
      "TPMS",
      "DFMS",
    ],
    garantia: "3 años o 100.000 km",
  },
  {
    name: "Ora 3",
    model: "SUV Eléctrico",
    slug: "ora-3",
    image: "/ora-3-beige.jpg",
    price: "Consultar",
    features: {
      engine: "100% Eléctrico",
      transmission: "Automática",
      seats: "5 Pasajeros",
    },
    badge: "Eléctrico",
    description:
      "El ORA 3 es la nueva generación de movilidad sustentable. Un SUV 100% eléctrico que combina gran autonomía, tecnología de punta y máxima seguridad, perfecto para la ciudad moderna.",
    specs: {
      motor: "Motor eléctrico 126 kW",
      potencia: "169 HP",
      torque: "250 Nm",
      bateria: "LFP 48 kWh",
      autonomia: "370 km NEDC / 310 km WLTP",
      cargaRapida: "DC (10-80%) en 40 min",
      cargaLenta: "AC (15-80%) en 5.5 hs",
      llantas: '18" con neumáticos 215/50 R18',
      dimensiones: "4.235 x 1.825 x 1.603 mm",
      entreEjes: "2.650 mm",
      capacidadBaul: "282 a 858 L",
    },
    equipamiento: [
      'Pantalla multimedia 10.25"',
      'Tablero digital 10.25"',
      "Apple CarPlay & Android Auto inalámbrico",
      "Tapizados de cuero",
      "Asientos eléctricos (conductor 6 pos., acompañante 4 pos.)",
      "Climatizador automático",
      "Techo panorámico con apertura",
      "Encendido inteligente y acceso keyless",
      "Iluminación full LED",
      "Luces altas automáticas",
      "Sensor crepuscular",
    ],
    seguridad: [
      "7 airbags (frontales, laterales, cortina y central)",
      "Frenos a disco en las 4 ruedas",
      "ABS, ESC, TCS",
      "Control crucero adaptativo",
      "Frenado autónomo",
      "Asistente de carril",
      "Cámara 360°",
      "Sensores de proximidad",
    ],
    garantia: "Vehículo: 7 años o 150.000 km | Batería: 8 años o 150.000 km",
  },
  {
    name: "H6 GT",
    model: "SUV Deportivo",
    slug: "h6-gt",
    image: "/h6-gt-azul-oscuro.jpg",
    price: "Consultar",
    features: {
      engine: "2.0L Turbo",
      transmission: "DCT 7 velocidades",
      seats: "5 Pasajeros",
    },
    badge: "Deportivo",
    description:
      "El Haval H6 GT es la versión deportiva del exitoso H6. Con tracción 4WD, motor turbo de 201 HP y un diseño agresivo, combina performance y lujo en un paquete irresistible.",
    specs: {
      motor: "2.0L Turbo 4 cilindros",
      potencia: "201 HP (6.000 rpm)",
      torque: "320 Nm (1.500-4.400 rpm)",
      transmision: "DCT 7 velocidades",
      traccion: "4WD",
      dimensiones: "4.653 x 1.886 x 1.730 mm",
      entreEjes: "2.738 mm",
      pesoBruto: "2.075 kg",
    },
    equipamiento: [
      "Techo panorámico",
      "Asientos calefaccionados y ventilados",
      'Pantalla multimedia 10.3"',
      "Apple CarPlay + Android Auto",
      "Carga inalámbrica",
      "Tapizado cuero",
      "Apertura eléctrica de baúl",
    ],
    seguridad: [
      "6 airbags",
      "AEB (Frenado Autónomo)",
      "LKA (Asistente de Carril)",
      "ACC (Control de Crucero Adaptativo)",
      "BSD (Detección de Punto Ciego)",
      "Cámara 360°",
      "TPMS",
      "HUD (Head-Up Display)",
    ],
    garantia: "3 años o 100.000 km",
  },
  {
    name: "Poer Elite",
    model: "Pick-up 4x4 Diesel",
    slug: "poer-elite",
    image: "/poer-elite-azul.jpg",
    gallery: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/poer-jchbZt1hJLARTXaqBf43v1VQF58x74.jpg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Interior-Poer-nmGT1yuCUMmdjJPeMG5ePBsx4UJdJI.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/poer-interior1-pN52iVpCF9sn3mytNy7WCF0dPVvwya.webp",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Asientos-traseros-Poer-qChOtgGYcTZ9y8naldCpyBOtnLT3QJ.webp",
    ],
    price: "Consultar",
    features: {
      engine: "2.0L Turbo Diesel",
      transmission: "Automática ZF 8 vel.",
      seats: "5 Pasajeros",
    },
    badge: "Pick-up",
    description:
      "La GWM Poer Luxury es la pick-up 4x4 que combina capacidad de carga, confort y tecnología. Con motor diesel turbo, transmisión ZF de 8 velocidades y tracción 4x4 automática, está lista para el trabajo y la aventura.",
    specs: {
      motor: "2.0L Diesel Turbo (VGT)",
      potencia: "163 HP",
      torque: "400 Nm (1.500-2.500 rpm)",
      transmision: "Automática ZF 8 velocidades",
      traccion: "4x4 automática Torque on Demand (TOD)",
      dimensiones: "5.410 x 1.934 x 1.886 mm",
      cajaCarga: "1.520 x 1.520 x 538 mm",
      pesoBruto: "2.967 kg",
      cargaUtil: "975 kg",
      tanque: "80 L",
    },
    equipamiento: [
      "Tapizado cuero",
      "Climatizador automático",
      'Pantalla 9"',
      "Techo eléctrico",
      "Cargador inalámbrico",
      "Cámara 360°",
      "Asientos eléctricos calefaccionados",
    ],
    seguridad: [
      "6 airbags",
      "AEB (Frenado Autónomo)",
      "FCW (Alerta de Colisión Frontal)",
      "LKA (Asistente de Carril)",
      "ACC (Control de Crucero Adaptativo)",
      "Control de descenso",
      "TPMS",
    ],
    garantia: "6 años o 150.000 km",
  },
]
